import { keyboard } from "../default-keyboards";
import { justIntonationRatios } from "../justi-intonation-ratios";

const harmoniousKeyboard: keyboard = {
  name: { name: "harmonious" },
  " ": {
    name: "gamelan1",
    playType: "SINGLE",
    playbackRate: 0.5,
    volume: -5,
    randomize: false,
  },
  a: {
    name: "harmonium",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  b: {
    name: "gamelan1",
    playType: "SINGLE",
    playbackRate: justIntonationRatios[4],
    volume: -5,
    randomize: false,
  },
  c: {
    name: "gamelan1",
    playType: "SINGLE",
    playbackRate: justIntonationRatios[2],
    volume: -5,
    randomize: false,
  },
  d: {
    name: "harmonium",
    playType: "LOOP",
    playbackRate: justIntonationRatios[2],
    volume: 0,
    randomize: false,
  },
  e: {
    name: "voice",
    playType: "LOOP",
    playbackRate: justIntonationRatios[2],
    volume: 0,
    randomize: false,
  },
  f: {
    name: "harmonium",
    playType: "LOOP",
    playbackRate: justIntonationRatios[3],
    volume: 0,
    randomize: false,
  },
  g: {
    name: "harmonium",
    playType: "LOOP",
    playbackRate: justIntonationRatios[4],
    volume: 0,
    randomize: false,
  },
  h: {
    name: "harmonium",
    playType: "LOOP",
    playbackRate: justIntonationRatios[5],
    volume: 0,
    randomize: false,
  },
  i: {
    name: "voice",
    playType: "LOOP",
    playbackRate: 2,
    volume: 0,
    randomize: false,
  },
  j: {
    name: "harmonium",
    playType: "LOOP",
    playbackRate: justIntonationRatios[6],
    volume: 0,
    randomize: false,
  },
  k: {
    name: "harmonium",
    playType: "LOOP",
    playbackRate: 2,
    volume: 0,
    randomize: false,
  },
  l: {
    name: "harmonium",
    playType: "LOOP",
    playbackRate: 2 * justIntonationRatios[1],
    volume: 0,
    randomize: false,
  },
  m: {
    name: "gamelan1",
    playType: "SINGLE",
    playbackRate: justIntonationRatios[6],
    volume: -5,
    randomize: false,
  },
  n: {
    name: "gamelan1",
    playType: "SINGLE",
    playbackRate: justIntonationRatios[5],
    volume: -5,
    randomize: false,
  },
  o: {
    name: "voice",
    playType: "LOOP",
    playbackRate: 2 * justIntonationRatios[1],
    volume: 0,
    randomize: false,
  },
  p: {
    name: "voice",
    playType: "LOOP",
    playbackRate: 2 * justIntonationRatios[2],
    volume: 0,
    randomize: false,
  },
  q: {
    name: "voice",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  r: {
    name: "voice",
    playType: "LOOP",
    playbackRate: justIntonationRatios[3],
    volume: 0,
    randomize: false,
  },
  s: {
    name: "harmonium",
    playType: "LOOP",
    playbackRate: justIntonationRatios[1],
    volume: 0,
    randomize: false,
  },
  t: {
    name: "voice",
    playType: "LOOP",
    playbackRate: justIntonationRatios[4],
    volume: 0,
    randomize: false,
  },
  u: {
    name: "voice",
    playType: "LOOP",
    playbackRate: justIntonationRatios[6],
    volume: 0,
    randomize: false,
  },
  v: {
    name: "gamelan1",
    playType: "SINGLE",
    playbackRate: justIntonationRatios[3],
    volume: -5,
    randomize: false,
  },
  w: {
    name: "voice",
    playType: "LOOP",
    playbackRate: justIntonationRatios[1],
    volume: 0,
    randomize: false,
  },
  x: {
    name: "gamelan1",
    playType: "SINGLE",
    playbackRate: justIntonationRatios[1],
    volume: -5,
    randomize: false,
  },
  y: {
    name: "voice",
    playType: "LOOP",
    playbackRate: justIntonationRatios[5],
    volume: 0,
    randomize: false,
  },
  z: {
    name: "gamelan1",
    playType: "SINGLE",
    playbackRate: 1,
    volume: -5,
    randomize: false,
  },
  "0": {
    name: "piano",
    playType: "SINGLE",
    playbackRate: 2 * justIntonationRatios[2],
    volume: 0,
    randomize: false,
  },
  "1": {
    name: "piano",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "2": {
    name: "piano",
    playType: "SINGLE",
    playbackRate: justIntonationRatios[1],
    volume: 0,
    randomize: false,
  },
  "3": {
    name: "piano",
    playType: "SINGLE",
    playbackRate: justIntonationRatios[2],
    volume: 0,
    randomize: false,
  },
  "4": {
    name: "piano",
    playType: "SINGLE",
    playbackRate: justIntonationRatios[3],
    volume: 0,
    randomize: false,
  },
  "5": {
    name: "piano",
    playType: "SINGLE",
    playbackRate: justIntonationRatios[4],
    volume: 0,
    randomize: false,
  },
  "6": {
    name: "piano",
    playType: "SINGLE",
    playbackRate: justIntonationRatios[5],
    volume: 0,
    randomize: false,
  },
  "7": {
    name: "piano",
    playType: "SINGLE",
    playbackRate: justIntonationRatios[6],
    volume: 0,
    randomize: false,
  },
  "8": {
    name: "piano",
    playType: "SINGLE",
    playbackRate: 2,
    volume: 0,
    randomize: false,
  },
  "9": {
    name: "piano",
    playType: "SINGLE",
    playbackRate: 2 * justIntonationRatios[1],
    volume: 0,
    randomize: false,
  },
  ",": {
    name: "gamelan1",
    playType: "SINGLE",
    playbackRate: 2,
    volume: -5,
    randomize: false,
  },
  ".": {
    name: "gamelan1",
    playType: "RAPID",
    playbackRate: 1,
    volume: -10,
    randomize: false,
  },
  "?": {
    name: "gamelan1",
    playType: "RAPID",
    playbackRate: 2,
    volume: -10,
    randomize: false,
  },
  ";": {
    name: "harmonium",
    playType: "LOOP",
    playbackRate: 2 * justIntonationRatios[2],
    volume: 0,
    randomize: false,
  },
};

export default harmoniousKeyboard;
