import { keyboard } from '../default-keyboards';
import { justIntonationRatios } from '../justi-intonation-ratios';

const harmoniousKeyboard: keyboard = {
  name: { name: 'harmonious' },
  ' ': {
    name: 'gamelan1',
    playType: 'SINGLE',
    playbackRate: 0.5,
    volume: -5,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  a: {
    name: 'harmonium',
    playType: 'LOOP',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  b: {
    name: 'gamelan1',
    playType: 'SINGLE',
    playbackRate: justIntonationRatios[4],
    volume: -5,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  c: {
    name: 'gamelan1',
    playType: 'SINGLE',
    playbackRate: justIntonationRatios[2],
    volume: -5,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  d: {
    name: 'harmonium',
    playType: 'LOOP',
    playbackRate: justIntonationRatios[2],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  e: {
    name: 'voice',
    playType: 'LOOP',
    playbackRate: justIntonationRatios[2],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  f: {
    name: 'harmonium',
    playType: 'LOOP',
    playbackRate: justIntonationRatios[3],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  g: {
    name: 'harmonium',
    playType: 'LOOP',
    playbackRate: justIntonationRatios[4],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  h: {
    name: 'harmonium',
    playType: 'LOOP',
    playbackRate: justIntonationRatios[5],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  i: {
    name: 'voice',
    playType: 'LOOP',
    playbackRate: 2,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  j: {
    name: 'harmonium',
    playType: 'LOOP',
    playbackRate: justIntonationRatios[6],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  k: {
    name: 'harmonium',
    playType: 'LOOP',
    playbackRate: 2,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  l: {
    name: 'harmonium',
    playType: 'LOOP',
    playbackRate: 2 * justIntonationRatios[1],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  m: {
    name: 'gamelan1',
    playType: 'SINGLE',
    playbackRate: justIntonationRatios[6],
    volume: -5,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  n: {
    name: 'gamelan1',
    playType: 'SINGLE',
    playbackRate: justIntonationRatios[5],
    volume: -5,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  o: {
    name: 'voice',
    playType: 'LOOP',
    playbackRate: 2 * justIntonationRatios[1],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  p: {
    name: 'voice',
    playType: 'LOOP',
    playbackRate: 2 * justIntonationRatios[2],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  q: {
    name: 'voice',
    playType: 'LOOP',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  r: {
    name: 'voice',
    playType: 'LOOP',
    playbackRate: justIntonationRatios[3],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  s: {
    name: 'harmonium',
    playType: 'LOOP',
    playbackRate: justIntonationRatios[1],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  t: {
    name: 'voice',
    playType: 'LOOP',
    playbackRate: justIntonationRatios[4],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  u: {
    name: 'voice',
    playType: 'LOOP',
    playbackRate: justIntonationRatios[6],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  v: {
    name: 'gamelan1',
    playType: 'SINGLE',
    playbackRate: justIntonationRatios[3],
    volume: -5,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  w: {
    name: 'voice',
    playType: 'LOOP',
    playbackRate: justIntonationRatios[1],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  x: {
    name: 'gamelan1',
    playType: 'SINGLE',
    playbackRate: justIntonationRatios[1],
    volume: -5,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  y: {
    name: 'voice',
    playType: 'LOOP',
    playbackRate: justIntonationRatios[5],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  z: {
    name: 'gamelan1',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: -5,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  '0': {
    name: 'piano',
    playType: 'SINGLE',
    playbackRate: 2 * justIntonationRatios[2],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  '1': {
    name: 'piano',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  '2': {
    name: 'piano',
    playType: 'SINGLE',
    playbackRate: justIntonationRatios[1],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  '3': {
    name: 'piano',
    playType: 'SINGLE',
    playbackRate: justIntonationRatios[2],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  '4': {
    name: 'piano',
    playType: 'SINGLE',
    playbackRate: justIntonationRatios[3],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  '5': {
    name: 'piano',
    playType: 'SINGLE',
    playbackRate: justIntonationRatios[4],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  '6': {
    name: 'piano',
    playType: 'SINGLE',
    playbackRate: justIntonationRatios[5],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  '7': {
    name: 'piano',
    playType: 'SINGLE',
    playbackRate: justIntonationRatios[6],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  '8': {
    name: 'piano',
    playType: 'SINGLE',
    playbackRate: 2,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  '9': {
    name: 'piano',
    playType: 'SINGLE',
    playbackRate: 2 * justIntonationRatios[1],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  ',': {
    name: 'gamelan1',
    playType: 'SINGLE',
    playbackRate: 2,
    volume: -5,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  '.': {
    name: 'gamelan1',
    playType: 'RAPID',
    playbackRate: 1,
    volume: -10,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  '?': {
    name: 'gamelan1',
    playType: 'RAPID',
    playbackRate: 2,
    volume: -10,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
  ';': {
    name: 'harmonium',
    playType: 'LOOP',
    playbackRate: 2 * justIntonationRatios[2],
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'Just intonation',
  },
};

export default harmoniousKeyboard;
