import { keyboard } from '../default-keyboards';

const mainKeyboard: keyboard = {
  name: { name: 'main' },
  ' ': {
    name: 'kick',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  a: {
    name: 'kick',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  b: {
    name: 'bugara1',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  c: {
    name: 'bugara2',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  d: {
    name: 'ceng',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  e: {
    name: 'demung1',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  f: {
    name: 'demung2',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  g: {
    name: 'demung3',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  h: {
    name: 'djembe1',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  i: {
    name: 'djembe2',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  j: {
    name: 'djembe3',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  k: {
    name: 'jegog',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  l: {
    name: 'hat',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  m: {
    name: 'kantilan',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  n: {
    name: 'kalimba',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  o: {
    name: 'kazoo',
    playType: 'LOOP',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  p: {
    name: 'kempur',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  q: {
    name: 'piano',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',

    attack: 0.8,
    release: 0.8,
  },
  r: {
    name: 'singing',
    playType: 'LOOP',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  s: {
    name: 'snare',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  t: {
    name: 'spring',
    playType: 'RAPID',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  u: {
    name: 'tambura',
    playType: 'LOOP',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  v: {
    name: 'tom',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  w: {
    name: 'trumpet',
    playType: 'LOOP',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  x: {
    name: 'gamelan1',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  y: {
    name: 'gamelan2',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  z: {
    name: 'gamelan3',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  '0': {
    name: 'ruler',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  '1': {
    name: 'bowl',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  '2': {
    name: 'harmonium',
    playType: 'LOOP',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  '3': {
    name: 'oboe',
    playType: 'LOOP',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  '4': {
    name: 'organ',
    playType: 'LOOP',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  '5': {
    name: 'oud',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  '6': {
    name: 'rebana',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  '7': {
    name: 'ride',
    playType: 'SINGLE',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  '8': {
    name: 'hiss',
    playType: 'LOOP',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  '9': {
    name: 'voice',
    playType: 'LOOP',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  ',': {
    name: 'voice',
    playType: 'LOOP',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  '.': {
    name: 'voice',
    playType: 'LOOP',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  '?': {
    name: 'voice',
    playType: 'LOOP',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
  ';': {
    name: 'voice',
    playType: 'LOOP',
    playbackRate: 1,
    volume: 0,
    randomize: false,
    octave: 1,
    tuning: 'any',
    attack: 0.8,
    release: 0.8,
  },
};

export default mainKeyboard;
