type keyboard = {
  [key: string]: {
    name: string;
    playType?: "SINGLE" | "RAPID" | "LOOP" | undefined;
    playbackRate?: number;
    volume?: number;
    randomize?: boolean;
  };
};

export const mainKeyboard: keyboard = {
  name: { name: "main" },
  " ": {
    name: "kick",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  a: {
    name: "kick",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  b: {
    name: "bugara1",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  c: {
    name: "bugara2",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  d: {
    name: "ceng",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  e: {
    name: "demung1",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  f: {
    name: "demung2",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  g: {
    name: "demung3",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  h: {
    name: "djembe1",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  i: {
    name: "djembe2",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  j: {
    name: "djembe3",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  k: {
    name: "jegog",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  l: {
    name: "hat",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  m: {
    name: "kantilan",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  n: {
    name: "kalimba",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  o: {
    name: "kazoo",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  p: {
    name: "kempur",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  q: {
    name: "piano",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  r: {
    name: "singing",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  s: {
    name: "snare",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  t: {
    name: "spring",
    playType: "RAPID",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  u: {
    name: "tambura",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  v: {
    name: "tom",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  w: {
    name: "trumpet",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  x: {
    name: "gamelan1",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  y: {
    name: "gamelan2",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  z: {
    name: "gamelan3",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "0": {
    name: "ruler",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "1": {
    name: "bowl",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "2": {
    name: "harmonium",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "3": {
    name: "oboe",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "4": {
    name: "organ",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "5": {
    name: "oud",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "6": {
    name: "rebana",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "7": {
    name: "ride",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "8": {
    name: "hiss",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "9": {
    name: "voice",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
};

export const percussionKeyboard: keyboard = {
  name: { name: "percussion" },
  " ": {
    name: "kick",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  a: {
    name: "kick",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  b: {
    name: "bugara1",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  c: {
    name: "bugara2",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  d: {
    name: "ceng",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  e: {
    name: "demung1",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  f: {
    name: "demung2",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  g: {
    name: "demung3",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  h: {
    name: "djembe1",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  i: {
    name: "djembe2",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  j: {
    name: "djembe3",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  k: {
    name: "jegog",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  l: {
    name: "hat",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  m: {
    name: "kantilan",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  n: {
    name: "kalimba",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  o: {
    name: "kazoo",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  p: {
    name: "kempur",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  q: {
    name: "piano",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  r: {
    name: "singing",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  s: {
    name: "snare",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  t: {
    name: "spring",
    playType: "RAPID",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  u: {
    name: "tambura",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  v: {
    name: "tom",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  w: {
    name: "trumpet",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  x: {
    name: "gamelan1",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  y: {
    name: "gamelan2",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  z: {
    name: "gamelan3",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "0": {
    name: "ruler",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "1": {
    name: "bowl",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "2": {
    name: "harmonium",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "3": {
    name: "oboe",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "4": {
    name: "organ",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "5": {
    name: "oud",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "6": {
    name: "rebana",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "7": {
    name: "ride",
    playType: "SINGLE",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "8": {
    name: "hiss",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
  "9": {
    name: "voice",
    playType: "LOOP",
    playbackRate: 1,
    volume: 0,
    randomize: false,
  },
};
