type keyboard = {
  [key: string]: { name: string; playType: null | "SINGLE" | "RAPID" | "LOOP" };
};
export const mainKeyboard: keyboard = {
  name: { name: "main", playType: null },
  " ": { name: "kick", playType: "SINGLE" },
  a: { name: "kick", playType: "SINGLE" },
  b: { name: "bugara1", playType: "SINGLE" },
  c: { name: "bugara2", playType: "SINGLE" },
  d: { name: "ceng", playType: "SINGLE" },
  e: { name: "demung1", playType: "SINGLE" },
  f: { name: "demung2", playType: "SINGLE" },
  g: { name: "demung3", playType: "SINGLE" },
  h: { name: "djembe1", playType: "SINGLE" },
  i: { name: "djembe2", playType: "SINGLE" },
  j: { name: "djembe3", playType: "SINGLE" },
  k: { name: "jegog", playType: "SINGLE" },
  l: { name: "hat", playType: "SINGLE" },
  m: { name: "kantilan", playType: "SINGLE" },
  n: { name: "kalimba", playType: "SINGLE" },
  o: { name: "kazoo", playType: "LOOP" },
  p: { name: "kempur", playType: "SINGLE" },
  q: { name: "piano", playType: "SINGLE" },
  r: { name: "singing", playType: "LOOP" },
  s: { name: "snare", playType: "SINGLE" },
  t: { name: "spring", playType: "RAPID" },
  u: { name: "tambura", playType: "LOOP" },
  v: { name: "tom", playType: "SINGLE" },
  w: { name: "trumpet", playType: "LOOP" },
  x: { name: "gamelan1", playType: "SINGLE" },
  y: { name: "gamelan2", playType: "SINGLE" },
  z: { name: "gamelan3", playType: "LOOP" },
  "0": { name: "ruler", playType: "SINGLE" },
  "1": { name: "bowl", playType: "SINGLE" },
  "2": { name: "harmonium", playType: "LOOP" },
  "3": { name: "oboe", playType: "LOOP" },
  "4": { name: "organ", playType: "LOOP" },
  "5": { name: "oud", playType: "SINGLE" },
  "6": { name: "rebana", playType: "SINGLE" },
  "7": { name: "ride", playType: "SINGLE" },
  "8": { name: "hiss", playType: "LOOP" },
  "9": { name: "voice", playType: "LOOP" },
};

export const percussionKeyboard: keyboard = {
  name: { name: "main", playType: null },
  " ": { name: "kick", playType: "SINGLE" },
  a: { name: "kick", playType: "SINGLE" },
  b: { name: "bugara1", playType: "SINGLE" },
  c: { name: "bugara2", playType: "SINGLE" },
  d: { name: "ceng", playType: "SINGLE" },
  e: { name: "demung1", playType: "SINGLE" },
  f: { name: "demung2", playType: "SINGLE" },
  g: { name: "demung3", playType: "SINGLE" },
  h: { name: "djembe1", playType: "SINGLE" },
  i: { name: "djembe2", playType: "SINGLE" },
  j: { name: "djembe3", playType: "SINGLE" },
  k: { name: "jegog", playType: "SINGLE" },
  l: { name: "hat", playType: "SINGLE" },
  m: { name: "kantilan", playType: "SINGLE" },
  n: { name: "kalimba", playType: "SINGLE" },
  o: { name: "kazoo", playType: "LOOP" },
  p: { name: "kempur", playType: "SINGLE" },
  q: { name: "piano", playType: "SINGLE" },
  r: { name: "singing", playType: "LOOP" },
  s: { name: "snare", playType: "SINGLE" },
  t: { name: "spring", playType: "RAPID" },
  u: { name: "tambura", playType: "LOOP" },
  v: { name: "tom", playType: "SINGLE" },
  w: { name: "trumpet", playType: "LOOP" },
  x: { name: "gamelan1", playType: "SINGLE" },
  y: { name: "gamelan2", playType: "SINGLE" },
  z: { name: "gamelan3", playType: "LOOP" },
  "0": { name: "ruler", playType: "SINGLE" },
  "1": { name: "bowl", playType: "SINGLE" },
  "2": { name: "harmonium", playType: "LOOP" },
  "3": { name: "oboe", playType: "LOOP" },
  "4": { name: "organ", playType: "LOOP" },
  "5": { name: "oud", playType: "SINGLE" },
  "6": { name: "rebana", playType: "SINGLE" },
  "7": { name: "ride", playType: "SINGLE" },
  "8": { name: "hiss", playType: "LOOP" },
  "9": { name: "voice", playType: "LOOP" },
};
